#Nome do workflow, aparece na aba "Actions"
name: Pipeline CI/CD
#Definir quando o pipeline será disparado. Aqui especifica que, quando ocorrer um "push" na main branch, o pipeline será disparado.
on: 
  push:
    branches:
      -  main
    #Só dispara se os arquivos nessas pastas mudarem
    paths:
     #Só mudanças no código fonte
      - "/src/**"
      #Mudanças nos próprios pipelines
      - ".github/workflows/**"
  workflow_dispatch: #habilitar o botão "Run workflow" no GitHub Actions

#Conjunto de passos (steps) do pipeline que está sendo criado
jobs:
  #Primeiro job: build
  build:
    #Imagem da máquina usada no CI
    runs-on: ubuntu-latest
    #Passos que serão realizados
    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      #Instala o Node na máquina que será criada para rodar o código
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          #Especifica a versão do Node
          node-version: '22'
          cache: "npm"
          cache-dependency-path: package-lock.json
          
      - name: Instalação das dependências
        run: npm install
        
        #Roda o build na máquina virtual criada
      - name: Rodar o build
        run: npm run build
        #Especifica as variáveis que foram configuradas no GitHub Actions
        env:
          TMDB_API_URL: ${{ vars.TMDB_API_URL }}
          TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
          NEXT_PUBLIC_TMDB_API_IMG_URL: ${{ vars.NEXT_PUBLIC_TMDB_API_IMG_URL }}
          
  tests:
        #Imagem da máquina usada no CI
        runs-on: ubuntu-latest
        #Precisa que o build já tenha sido feito
        needs: build
        steps:
          - name: Checkout do código
            uses: actions/checkout@v6

          #Instala o Node na máquina que será criada para rodar o código
          - name: Instalação do Node
            uses: actions/setup-node@v4
            with:
              #Especifica a versão do Node
              node-version: '22'
              cache: "npm"
              cache-dependency-path: "./cinelista-nextjs/package-lock.json"
          
          - name: Instalação das dependências
            run: npm install
        
          #Roda o lint na máquina virtual criada
          - name: Rodar lint
            run: npm run lint
           
          - name: Verificar formatação
            run: npm run format
            
          #Roda os testes na máquina virtual criada
          - name: Rodar testes
            run: npm run test
