#Nome do workflow, aparece na aba "Actions"
name: Pipeline CI/CD
#Definir quando o pipeline será disparado. Aqui especifica que, quando ocorrer um "push" na main branch, o pipeline será disparado.
on: 
  push:
    branches:
      -  main
    #Só dispara se os arquivos nessas pastas mudarem
    paths:
     #Só mudanças no código fonte
      - "EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs/src/**"
      #Mudanças nos próprios pipelines
      - ".github/workflows/**"
  workflow_dispatch: #habilitar o botão "Run workflow" no GitHub Actions

#Conjunto de passos (steps) do pipeline que está sendo criado
jobs:
  #Primeiro job: build
  build:
    #Imagem da máquina usada no CI
    runs-on: ubuntu-latest
            # Define o caminho exato até a pasta do projeto Next.js, pelo fato do arquivo yml não estar no mesmo diretório do projeto
    defaults:
      run:
        working-directory: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs"
    #Passos que serão realizados
    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      #Instala o Node na máquina que será criada para rodar o código
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          #Especifica a versão do Node
          node-version: '20'
          cache: "npm"
          cache-dependency-path: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs/package-lock.json"
          
      - name: Instalação das dependências
        run: npm install
        
        #Roda o build na máquina virtual criada
      - name: Rodar o build
        run: npm run build
        #Especifica as variáveis que foram configuradas no GitHub Actions
        env:
          TMDB_API_URL: ${{ vars.TMDB_API_URL }}
          TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
          NEXT_PUBLIC_TMDB_API_IMG_URL: ${{ vars.NEXT_PUBLIC_TMDB_API_IMG_URL }}
          
  tests:
        #Imagem da máquina usada no CI
        runs-on: ubuntu-latest
            # Define o caminho exato até a pasta do projeto Next.js, pelo fato do arquivo yml não estar no mesmo diretório do projeto
        defaults:
          run:
            working-directory: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs"
            
        #Precisa que o build já tenha sido feito
        needs: build
        steps:
          - name: Checkout do código
            uses: actions/checkout@v6

          #Instala o Node na máquina que será criada para rodar o código
          - name: Instalação do Node
            uses: actions/setup-node@v4
            with:
              #Especifica a versão do Node
              node-version: '20'
              cache: "npm"
              cache-dependency-path: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs/package-lock.json"
          
          - name: Instalação das dependências
            run: npm install
        
          #Roda o lint na máquina virtual criada
          - name: Rodar lint
            run: npm run lint
           
          - name: Verificar formatação
            run: npm run format
            
          #Roda os testes na máquina virtual criada
          - name: Rodar testes
            run: npm run test

       deploy:
        #Imagem da máquina usada no CI
        runs-on: ubuntu-latest
            # Define o caminho exato até a pasta do projeto Next.js, pelo fato do arquivo yml não estar no mesmo diretório do projeto
        defaults:
          run:
            working-directory: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs"
            
        #Precisa que o build já tenha sido feito
        needs: tests
        steps:
          - name: Checkout do código
            uses: actions/checkout@v6

          #Instala o Node na máquina que será criada para rodar o código
          - name: Instalação do Node
            uses: actions/setup-node@v4
            with:
              #Especifica a versão do Node
              node-version: '20'
              cache: "npm"
              cache-dependency-path: "./EBAC/1 - engFrontEnd/j - React/exercicios/cinelista-nextjs/package-lock.json"

          #Instalação necessária na máquina virtual da CLI da Vercel
          - name: Instalação Vercel CLI
            run: npm install -g vercel@latest
        
          #Roda o lint na máquina virtual criada
          - name: Deploy para a Vercel
          #Busca a variável salva em secrets and variables
            run: vercel --prod --yes --token=${{secrets.VERCEL_TOKEN}}
             #Especifica as variáveis que foram configuradas no GitHub Actions no caso do deploy
            env:
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
